### ISSUE TITLE
Repeated call searching xpath

### ISSUE THREAD

**Issue by Adman** [mrshu/python-imhdsk-api#3]
Is there any reason to repeat this line? Same call on line [103](https://github.com/mrshu/python-imhdsk-api/blob/master/imhdsk/__init__.py#L103)

https://github.com/mrshu/python-imhdsk-api/blob/34f84d36c6686af4b954c94edd22220a9bd32468/imhdsk/__init__.py#L106

**Comment by mrshu** [comment]
I honestly do not think so @Adman, but with no tests it's tough to say :)

If it works without it, I do not see why would it be necessary/important.
